css-layout-classes.
Alankim56/m1-1222-code-solutions pull request #16
Opened 2022-12-19 01:10 UTC by Alankim56

![css-layout-classes 1218](https://user-images.githubusercontent.com/97194926/208329858-1dd20e79-0a43-4bb8-bed0-c5105fe88a8d.png)

2022-12-19 05:07 UTC, Alankim56 commented
![1218 css-layout-classes adjusted ](https://user-images.githubusercontent.com/97194926/208351950-d80a8506-f1f0-4345-83ae-0a3c025505ed.png)

2022-12-19 17:15 UTC, scrumptiousdev requested changes

2022-12-19 17:15 UTC, scrumptiousdev commented on css-layout-classes/styles.css
> +#container {
It's best practice not to use id in order to style element

2022-12-19 17:15 UTC, scrumptiousdev commented on css-layout-classes/styles.css
> +  height: 100%;
`.row` shouldn't need any width or height

2022-12-19 17:15 UTC, scrumptiousdev commented on css-layout-classes/styles.css
> +  flex-basis: 66.6%;
This is totally fine but it's better if we could rely on `calc` so it does pixel perfect calculations

2022-12-19 17:15 UTC, scrumptiousdev commented on css-layout-classes/styles.css
> +  flex-basis: calc(100%/1);
In this case, it doesn't need any calculation so it can be just `100%` without `calc`

2022-12-19 17:15 UTC, scrumptiousdev commented on css-layout-classes/index.html
> +          <img src="images/ness.png" class="four" alt="Ness">
Each image needs to be wrapped in column with 1/4

2022-12-19 17:15 UTC, scrumptiousdev commented on css-layout-classes/styles.css
> +}
If we wrap each image with column with correct width then we won't need any of image sizings above

2022-12-21 03:31 UTC, scrumptiousdev approved these changes
Approved!

2022-12-21 04:30 UTC, merged