Completed two-column-layout.
Alankim56/m1-1222-code-solutions pull request #21
Opened 2022-12-26 20:28 UTC by Alankim56

![2-column-layout](https://user-images.githubusercontent.com/97194926/209581533-b62f8c36-5868-441e-b6a1-16627a61aaba.png)

2022-12-26 23:45 UTC, scrumptiousdev requested changes
Within each column, you should rather utilize flex to create columns to separate image and text side by side

2022-12-26 23:45 UTC, scrumptiousdev commented on css-two-column-layout/styles.css
> +  width: 70;
This does not have any unit so it's not a valid CSS value

2022-12-26 23:45 UTC, scrumptiousdev commented on css-two-column-layout/styles.css
> +  width: 60%;
We shouldn't set width to h3 but rather depends text to fill the column

2022-12-26 23:45 UTC, scrumptiousdev commented on css-two-column-layout/styles.css
> +  margin-right: 180px;
We shouldn't use margins in order to position the texts

2022-12-26 23:45 UTC, scrumptiousdev commented on css-two-column-layout/styles.css
> +  float: left;
Float left is not needed on this exercise

2022-12-29 18:56 UTC, scrumptiousdev requested changes
Changes in progress?

2023-01-02 06:07 UTC, Alankim56 commented
![css-two-column](https://user-images.githubusercontent.com/97194926/210199339-1a1ab64c-74ed-45c2-b81c-27b199150a50.png)

2023-01-02 23:51 UTC, scrumptiousdev requested changes
What you want to do is to still use 1/2 columns. But within each 1/2 columns you can have a row and then columns within it

2023-01-04 01:46 UTC, scrumptiousdev approved these changes
Approved!

2023-01-04 02:48 UTC, merged