completed css-brochure-form.
Alankim56/m1-1222-code-solutions pull request #24
Opened 2023-01-02 04:16 UTC by Alankim56

![css brochure form ](https://user-images.githubusercontent.com/97194926/210194746-7da1b8f3-ffae-428f-9c75-ea35c67f208a.png)

2023-01-02 23:54 UTC, scrumptiousdev requested changes
Text fields need to have rounded corner (`border-style: round;` is not a valid css).

Also, labels need to be little bit indented rather than having text fields being indented to the right

2023-01-03 02:59 UTC, Alankim56 commented
![css brochure jan 2 2023](https://user-images.githubusercontent.com/97194926/210294943-35fc0cba-d1d8-4fe0-8127-06af50579fe7.png)

2023-01-04 01:44 UTC, scrumptiousdev requested changes
Everything looks good but let's clean things up!

2023-01-04 01:44 UTC, scrumptiousdev commented on css-brochure-form/index.html
> +      <div class="column-full center">
`.center` classes are not defined in css file so let's remove all from html

2023-01-04 01:44 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +  flex-direction: column;
`.row` shouldn't need both `width` and `flex-direction`, just `display: flex;`

2023-01-04 01:44 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +}
This `body` style is not doing anything so let's remove it

2023-01-04 01:44 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +  font-weight: 300px;
`font-weight` does not accept `px` unit as a valid value

2023-01-04 01:44 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +  font-weight: 50px;
font-weight does not accept `px` unit as a valid value

2023-01-04 01:44 UTC, scrumptiousdev commented on css-brochure-form/index.html
> +      <div class="button-column">
Instead of defining another `button-column`, we can do `class="column-full end"` => See another comment in CSS file about `end`

2023-01-04 01:44 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +.button-column {
We can rename this one to `.end`

2023-01-16 23:04 UTC, scrumptiousdev approved these changes
Approved!

2023-01-18 02:44 UTC, merged